# Site settings
title: Melanie Richards’s bucket list
email: hello@melanie-richards.com
url: "http://bucketlist.melanie-richards.com"
images: /assets/images/

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/_sass
  style: compressed